version: '3.8'

services:
  dev:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:80"
      - "443:443"
      - "53847:53847"

env_file:
  - .env